### PR TITLE
Upgrade get-pip.py script

### PR DESCRIPTION
**Pull request by TimothyKlim**

### CODE REVIEW

**Comment by tedder** [comment]
by "upgrade", you aren't changing the code, you are only changing the file permissions, right? This is lacking any description..

**Comment by TimothyKlim** [comment]
@tedder No, I copy-pasted new version of get-pip.py from `https://bootstrap.pypa.io/get-pip.py` to fix "base64 not found" error.

**Comment by TimothyKlim** [comment]
@tedder You're right, I didn't notice that I fixed it in wrong version of this repo. Thanks!

**Comment by defunctzombie** [comment]
Is this ready to go? Github can't display the diff cause it is too large, what changed in general for such a large diff?

**Pull request closed without merging**
