### PR TITLE
Updates for 2.7 python version

### PR DESCRIPTION
**Pull request by lazarus1331**
This will allow a portable version of pypy to be installed to coreos hosts. Also includes installation of pip and docker-py. Final results are a CoreOS host that can be provisioned with ansible and ansible-core-modules.

### CODE REVIEW

**Comment by lazarus1331** [comment]
get-pip.py can't find any python:
'''
TASK: [ansible-coreos-bootstrap | Copy get-pip.py] **************************** 
failed: [core-01] => {"failed": true}
msg: python isn't present on the system.  Unable to compute checksum
'''

**Comment by defunctzombie** [comment]
Wonder if others are having the same issue, I don't believe I have seen an issue raised about not being able to find python binary tho maybe something changed in coreos? I suppose since we install into /home/coreos/bin/python then having the script use that python makes sense.

**Comment by lazarus1331** [comment]
changing the python in the get-pip.py actually had no effect; I needed to update the .bashrc in order for the python to be detected properly:
'''
$ vagrant ssh
Last login: Sat Dec 19 22:08:49 2015 from 10.0.2.2
CoreOS alpha (808.0.0)
core@core-01 ~ $ which python
which: no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)
core@core-01 ~ $ ls -a
.  ..  .ansible  .bash_logout  .bash_profile  .bashrc  .ssh  bin  pypy
core@core-01 ~ $ ls -al
total 48
drwxr-xr-x 6 core core 4096 Dec 19 22:08 .
drwxr-xr-x 3 root root 4096 Sep 17 04:41 ..
drwxr-xr-x 3 core core 4096 Dec 19 22:08 .ansible
lrwxrwxrwx 1 core core   33 Sep 17 04:41 .bash_logout -> ../../usr/share/skel/.bash_logout
lrwxrwxrwx 1 core core   34 Sep 17 04:41 .bash_profile -> ../../usr/share/skel/.bash_profile
lrwxrwxrwx 1 core core   28 Sep 17 04:41 .bashrc -> ../../usr/share/skel/.bashrc
drwx------ 3 core core 4096 Dec 19 22:08 .ssh
drwxr-xr-x 2 core core 4096 Dec 19 22:08 bin
drwxr-xr-x 9 core core 4096 Nov 19 16:59 pypy
core@core-01 ~ $ rm .bashrc
core@core-01 ~ $ vim .bashrc
core@core-01 ~ $ which python
which: no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)
core@core-01 ~ $ source .bashrc
core@core-01 ~ $ which python
/home/core/bin/python
core@core-01 ~ $ exit
'''
(NB: using this for testing https://github.com/coreos/coreos-vagrant)
using the portable version of pypy fixed library version mismatches that I was getting with CoreOS version above 645

**Comment by defunctzombie** [comment]
Fair, lets leave the file as is and just update the PATH in bashrc. Overriding bashrc fully tho is going to cause others to open reports about that behavior being wrong I suspect.

**Comment by defunctzombie** [comment]
Also, would be nice to review if this is an issue that you had or unrelated: https://github.com/defunctzombie/ansible-coreos-bootstrap/pull/21

**Comment by defunctzombie** [comment]
Seems this PR has started to add new unrelated elements.

**Pull request closed without merging**
